### ISSUE TITLE
How do you manage features in Bootstrap

### ISSUE THREAD

**Issue by bjankord** [mdo/ama#102]
I've got a few questions for you related to features in Bootstrap.

I was wondering if you could shed some light on how features make there way into Bootstrap? Kinda like the lifecycle of a feature, if you will. 

I'm curious about the process, from when a feature is requested to how it goes into a branch/branches?, tests it goes through, pull requests/reviews and finally merged into a stable release. Are there different flows for passive vs non-passive changes?

I'm also curious how you manage all the features / bug fixes / etc that go into a release and communicate those. Do you have an internal roadmap / set milestones?

Thanks!

**Comment by montogeek** [comment]
Yeah, still curious

**Comment by mdo** [comment]
Gah, I'll get to this eventually :D.

**Comment by bjankord** [comment]
Cool, no rush.

**Comment by martinvd** [comment]
:+1:

**Comment by bjankord** [comment]
[Motivation](https://www.youtube.com/watch?v=os6U77Hhm_s)

**Comment by mdo** [comment]
Holy shit it's out there! http://markdotto.com/2015/09/28/bootstrap-features/

**Comment by lachlanjc** [comment]
👏🙌

**Comment by bjankord** [comment]
Thanks @mdo! Pretty interesting to read through the process. :)
