### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by bvilla89** [mdo/ama#118]
Hi Mark,

Thank you so much for your work on Bootstrap. I was wondering if you could answer my two questions below. Thanks!

1) As the announcement that a Bootstrap 4 alpha is a couple weeks away was made over a month ago, I was wondering if you had any updates on when the alpha release may arrive?

2) In the current version of Bootstrap, pinned sidebars that transition to off-canvas with a hamburger button to toggle are difficult to pull off correctly. There are a lot of quirks, and the implementation we currently use in production causes some strange things to happen with our responsive tables at a certain breakpoint. Will Bootstrap 4 have a component specifically for sidebars that collapse on smaller screens? That would be awesome!

Thank you very much.

**Comment by bvilla89** [comment]
Any further updates at this time? :)

**Comment by mdo** [comment]
Negatory—status is same as last time :).

**Comment by Annonomus-Penguin** [comment]
Any further updates at *this time*? :grinning:

**Comment by mdo** [comment]
We'll post something when we have an update.

**Comment by cvrebert** [comment]
"a couple weeks" was overly optimistic :sweat_smile:

**Comment by Annonomus-Penguin** [comment]
Would you recommend just going on and starting working on a new project or just wait a bit more (I've already wait this long but have no idea how long until you get something out)? V4 is probably going to break backwards compatibility and I'm not exactly in the mood to redo a ton of work when a new framework comes out, although I certainly wouldn't mind changing a few things from an alpha release.

I'm not trying to annoy you, I'm just not sure what to do :smile:

**Comment by bvilla89** [comment]
^^ this. 

I am also about to start on a new project and really would prefer using v4 instead of starting on v3.x and then re-doing a bunch of markup
