### ISSUE TITLE
If you were to take a week-long vacation, what would it be?

### ISSUE THREAD

**Issue by ryanbraganza** [mdo/ama#152]
If you were to take a week-long vacation, what would it be?

**Comment by mdo** [comment]
A week long? Probably someplace in the Pacific Northwest. Something like Seattle. The problem with traveling any great distance is it takes the piss right out of you. Going overseas I'd want a few weeks. Given more time I want to go to Ireland, Iceland, or Poland.

**Comment by mdo** [comment]
Also Zurich and a few other Swiss towns were awesome—been there once before.
