### ISSUE TITLE
Thoughts on "Building Your Own Bootstrap" and sharing code with the app

### ISSUE THREAD

**Issue by marcelosomers** [mdo/ama#155]
Hey Mark,
When building a Pattern Library (aka ["building my own Bootstrap"](https://speakerdeck.com/mdo/build-your-own-bootstrap?slide=6)), do you have opinions on code sharing from the library to the project - especially in the case of scaling this to a huge organization like Salesforce and others have?

Obviously, this might change per project and organization, but I see a few solutions:
1. Build the pattern library into the app and have them share a CSS file to keep it "living" _(this only works if you have a single app)_
2. Build the pattern library as it's own project and someone can download and insert it into a new project as needed (like one might do with Bootstrap)
3. Build the pattern library as it's own project and import the code into your app using NPM, Bower, Rubygems, Git Submodules (whatever)

Have you experienced this? I'd love to get your take.

**Comment by mdo** [comment]
I've done all three approaches.

The first one works well enough in that you have a living styleguide that folks can reference as they work on the product you're building. Keeping both in sync is key, but the fact that it's there and using _real_ code is awesome. It's much less useful for libraries or toolkits you know need to be shared across multiple products or projects.

The second one is fine if you're building something generic enough for the masses—like Bootstrap. We don't have anything specific in there for a preferred backend language, deploy tool, etc. It's all about solving problems a little farther out than that. It's also great if you want to open source that stuff later.

Truth be told though, Bootstrap was started by developing a single application. I was designing an internal tool at Twitter with a team of developers. Anytime I knew there was a component others could use, I'd copy-paste it out into a separate repo and document it.

The third one is what we do with http://primercss.io, GitHub's internal CSS toolkit. It started out as the internal project of ours though—built into the main repo. It's included into `github/github` via Bower. Prior to open sourcing it it was a private repo (still include-able via Bower).

Nowadays, we basically do all our design and dev on `github/github`, modifying the Primer source files included via Bower. We test it out in a real application—GitHub.com—and when ready, open another PR for Primer to include those changes. That way they're always tested and in sync.

It's a bit of work, but worthwhile. In some cases we get public contributions to fix things, but most of Primer's development and design comes from us here at GitHub.

Hope that helps!

**Comment by marcelosomers** [comment]
Very helpful! My company is working toward option 3 as well, and building some tools to do that in a scalable way across clients.

Trying to better understand your workflow, I do have a few questions:
1. So changes are made in the bower_components folder in your `github/github` repo? How do you track the changes that are made in those files, since I assume you don't add the folder to the repo?
2. How would you scale primer across multiple apps (maybe you already do)? Apps that might have their own CSS updates that might not apply to primer?
3. How have you structured `github/primer` to determine if a new component needs to be added?
4. Have you incorporated any visual regression testing tools? What if a developer pushes a change to primer that breaks an unrelated app?

**Comment by mdo** [comment]
### 1. Handling changes

Those files are checked into Git, so they show up in our PRs to `github/github`.

### 2. Multiple apps

Primer is used across GitHub, Gist, some of our marketing sites, and several internal applications. For the most part those older apps are locked into things since we rarely update those tools once they're in a decent place. We have plenty of CSS outside Primer that extends Primer, handles things Primer doesn't, etc. Treat it like any other dependency—there is shared CSS and then there is unique CSS.

### 3. Components

The components for Primer—see https://github.com/primer/primer—have been largely unchanged since before I was hired. We add new things when someone on our CSS team notices a pattern of repetition across pages. For example, we had all custom layouts on several pages that needed two columns or so. I noticed, refactored by adding a basic grid system, and pushed that stuff to Primer.

### 4. Visual testing

No visual regression testing. Our stuff changes subtly so often—and we deploy dozens of times a day. Primer isn't in a place right now where changes impact lots of folks—hopefully soon though haha. Using semantic versioning helps—no breaking changes and what not unless it's a major version change. That's how we strive to do it in Bootstrap.

**Comment by marcelosomers** [comment]
Thanks, Mark!

One last question about handling changes. I've always assumed that any external dependency shouldn't be checked in. Every time I build an apps (on a developer machine or a build server), it re-runs `bower install`.

If you don't do this, then then technically primer is a one time dependency "clone," and theoretically could diverge from the master repo - correct? The only thing preventing that from happening are mindful developers that pull their changes back into `primer/primer`.

I only dig into this because it's the biggest gripe we've heard from developers with a pattern library. Our workflow is different: you go into the library's repo, make CSS changes there, then update your bower version in the main app and run `bower install` to see your changes. This can be arduous for sure.

**Comment by mdo** [comment]
The advantage to a manual workflow like ours is that you don't have unexpected breakages when deploying. Our exact flow looks like this example:
1. Decide to rewrite some part of our `buttons.scss` file in Primer.
2. Open a PR in `github/github` that modifiers `vendor/assets/bower_components/primer-css/scss/buttons.scss` there. This allows us to test these changes where they're most used.
3. Verify that the PR doesn't break anything, then create a new PR in Primer with those changes applied. Also update the version in that Primer PR and then merge and release it.
4. Once released, update the `bower.json` file in your PR on `github/github` with the new version number—or just run `bower update` if your version numbers are approximate there.
5. Then, merge into `master`.

It's more work, but pulling in new versions of dependencies at deploy time sounds like a recipe for disaster at some point.
