### ISSUE TITLE
Fontawesome with Hyde theme?

### ISSUE THREAD

**Issue by bekircem** [mdo/ama#160]
Hi. 

Fontawesome is not work with Hyde theme. 

Not work:

```
<link rel="stylesheet" href="{{ site.baseurl }}public/css/font-awesome.min.css">
```

It works:

``````
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">```

Why i can't use firstly method?
``````

**Comment by mdo** [comment]
If you have a copy of the font locally, and the font files, you should be able to use it. I can't help you with that though, sorry.
