### ISSUE TITLE
Why Bootstrap using different CSS for different devices

### ISSUE THREAD

**Issue by rohan-verma** [mdo/ama#162]
Hi,
I am learning Bootstrap and I have a question for the different classes used for different devices like col-_-_. If a beginner learns bootstrap then he should aware of each and every class for different screens.
In my opinion there should only one class like col-responsive which will take care for every device and screen using media queries(which are currently used by col-sm-\* , col-xs-*, etc).
So, the developer or one who is learning bootstrap doesn't aware for each different class.

**Comment by mdo** [comment]
You'll want to read the Bootstrap docs in more detail, but at a high level the Bootstrap grid column classes scale up automatically. For example, if you wanted the same three column layout on all devices, just use `.col-xs-4` for each column.
