### ISSUE TITLE
How could I change Git/GitHub terminology to better suit beginners?

### ISSUE THREAD

**Issue by ghost** [mdo/ama#163]
In lieu of me remapping words, how could a new version of Git/GitHub use terms a beginner could more intuitively understand, and hence could get them into using version control sooner? Like spin-off rather than fork (as fork and branch are synonymous to beginners), merge request rather than pull request (as merge implies two codebases to beginners)?

**Comment by mdo** [comment]
In what context? In some situations I think it's okay to substitute or change out words for things. For CLI usage that's less helpful, but for explaining concepts it's kinda fundamental. I imagine any public Git learning or training materials would be helpful places for suggestions and ideas.
