### ISSUE TITLE
What you think about RegExps idea? - Centralized place for regular expressions

### ISSUE THREAD

**Issue by tunnckoCore** [mdo/ama#165]
That's a big idea and project, and have many steps to do more.
- [RegExps Github Organization](https://github.com/regexps)
- [meta stuff repository](https://github.com/regexps/meta)
- [General discussion and roadmap](https://github.com/regexps/meta/issues/16)
- [more big and older "first hit" discussion](https://github.com/regexps/meta/issues/2)

In general  - centralized place for regular expression world for all languages. Just we are javascripters and we start with it.

[https://github.com/tunnckoCore/ama](https://github.com/tunnckoCore/messages)

**Comment by mdo** [comment]
Sounds rad! I don't write any regex myself, but I'm sure there's a use for collecting the resources :).
