### ISSUE TITLE
Do you use Atom?

### ISSUE THREAD

**Issue by coliff** [mdo/ama#166]
I hear that a lot of Sublime Text users are switching to Atom. Do you use it as your first-choice code editor? If not, why not.

**Comment by mdo** [comment]
I do now, yes. I used Sublime Text 2 for the last ~4 years until a few weeks ago. I had installed the OS X 10.11 beta and Sublime Text was a little wonky in fullscreen mode so I made the switch. It's finally fast enough for me, so I just went with it :).

**Comment by huphtur** [comment]
Might want to update your [about](http://markdotto.com/about/) page 😜

**Comment by mdo** [comment]
Done!
