### ISSUE TITLE
Question about Lanyon!

### ISSUE THREAD

**Issue by ghost** [mdo/ama#167]
Hello,

Thanks for making this wonderful layout for a website.
I'm working on this and I have a slight problem.
I succeeded deploying my "home" of the website into http://stanford.edu/~horray/  , which is great
but when I click the pages on the left banner, it leads to  http://stanford.edu/1People.html  and fails.
It should lead to http://stanford.edu/~horray/1People.html  , which gives the right link.
I suppose I have to change something in _config.yml, but I don't know what to do.
Please help me!

Mingyu Kang

**Comment by mdo** [comment]
You have to modify the `baseurl` option to include the `~horray` I believe.

**Comment by ghost** [comment]
This is my config.yml currently...
just to make sure I fixed every urls and links to stanford.edu/~horray
but still it doesn't work
Do you know any possible additional problem?

```
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           http://stanford.edu/~horray
relative_permalinks: http://stanford.edu/~horray

# Setup
title:               Stanford ATLAS
tagline:             'Fast TracKer'
description:         'A journey to the fundamentals of the universe!'
url:                 http://stanford.edu/~horray
baseurl:             http://stanford.edu/~horray
paginate:            5

# About/contact
author:
  name:              Lauren Tompkins
  url:               https://physics.stanford.edu/people/faculty/lauren-tompkins
  email:             laurenat@stanford.edu

# Custom vars
version:             1.0.0
```

**Comment by Andersos** [comment]
Try [Stackoverflow.com](http://stackoverflow.com/)
