### ISSUE TITLE
Bootstrap brand guidelines

### ISSUE THREAD

**Issue by jtrumbull** [mdo/ama#168]
Bootstrap's [brand guidelines](http://getbootstrap.com/about/#brand) state that they were inspired by MailChimp's Brand Assets. Does this include the legal section at the bottom the [page](http://mailchimp.com/about/brand-assets/#legal)? Particularly the bit about not altering the images in any way, or combining them with any other graphics.

For example: If I were to create a Bootstrap extension library of useful goodies and hosted a docs page, would I be free to use the Bootstrap mark in conjunction with a `glyphicon-plus-sign` (and possibly an alternative color scheme)? For clarity sake, the previous question is multi-faceted:
**1**. Would I need written consent from Bootstrap?
**2**. If so: How would I go about getting vetted for written consent?

Thanks in advance.

**Comment by mdo** [comment]
As long as it's clear enough it's not an official thing, you're good to go. The format and examples were inspired by Mailchimp's document, not the legalese.

**Comment by jtrumbull** [comment]
Thanks Mark. I will be sure to use the word "unofficial" in the jumbotron lead, add a disclaimer of non-affiliation, and link back to the Bootstrap project.

Keep up the awesomeness.

**Comment by mdo** [comment]
<3
