### ISSUE TITLE
Bootstrap Purple is from which A$AP Rocky Album Cover?

### ISSUE THREAD

**Issue by joshbuchea** [mdo/ama#169]
I just listened to Design Details Ep. #47 feat. you, and you mention that Bootstrap Purple came from an A$AP Rocky Album Cover. Very interesting hearing where others find their design inspiration. Just curious, can you remember which one?

**Comment by marionzualo** [comment]
In the podcast, @mdo, mentions a purple flag. So I'm assuming it is from the single Peso. http://genius.com/A-ap-rocky-peso-lyrics

**Comment by mdo** [comment]
That's the one!

**Comment by mdo** [comment]
![](http://images.rapgenius.com/6074980ea408ebe29f8a03d48d340f8a.900x900x1.jpg)

**Comment by mdo** [comment]
:grin:
