### ISSUE TITLE
My emails to GitHub's support are ignored. Suggestions?

### ISSUE THREAD

**Issue by inputsh** [mdo/ama#170]
I'm an owner of GitHub's Student Developer Pack. With it, I got a unique link to register a free `.me` domain using Namecheap. Unfortunately, I mistyped my email address using my unique link and I wasn't able to register my domain. I contacted Namecheap's support and they said to me that this problem should be resolved by GitHub's staff by giving me a new unique link.

I have contacted GitHub's support over and over again both on support@github.com and on education@github.com and every single one of my emails got ignored (I sent at least 3-4 of them during the last few months). I haven't received any response what so ever.

What should I do?

**Comment by mdo** [comment]
Well that's shitty. Sorry about that. I just bumped your support thread—I'll follow up tomorrow to see if anyone's replied.

**Comment by inputsh** [comment]
This has been the shittiest support experience I have ever encountered with (82 days have passed since I sent the first email, I just checked it) which annoys me big time because I [wrote an article](https://opensource.com/life/15/2/beginners-guide-github) a month before that (well, actually [a couple of months before](https://r3bl.github.io/en/why-github-is-my-favorite-company/), but it became popular once it was reposted to Opensource.com) where 50k+ readers have read that I stated that GitHub's support is awesome.

**Comment by mdo** [comment]
Totally understandable—you're not going to hear a counterargument from me on that. We should've at least told you we're working on it. I know nothing about the student packs or how they work on our end though so I can't give you an immediate fix I'm afraid. I'll keep looking into it though.

**Comment by inputsh** [comment]
Thanks, it feels good to get _any_ response from anyone from GitHub regarding this issue. I do hope that this will get resolved soon.

**Comment by mdo** [comment]
Early feedback from folks seems to indicate we might not be able to regenerate the Namecheap stuff, but still waiting to hear back from more people. Should have more info tomorrow.

**Comment by inputsh** [comment]
Well that's extremely weird considering that Namecheap specifically told me that you should be able to provide me with a new unique link.

**Comment by mdo** [comment]
We're in a holding pattern for the rest of the week it seems :. The point person for this stuff is out this week and we haven't gotten a hold of him just yet to see where he landed on helping others with problems like your own. I'll holler if I hear anything new.

**Comment by inputsh** [comment]
Well, waiting for a couple of more days is not a problem to me currently.

**Comment by mdo** [comment]
Hey, you should be hearing from someone on our support team tomorrow with a new link. Be on the look out for that and holler if you anything else comes up. I'll leave this open until I know for sure it's been resolved. Again, apologies for the black hole of communication. We'll do better next time <3.

**Comment by inputsh** [comment]
It's resolved, my site is now live on http://r3bl.me/. Thanks for everything. <3

**Comment by mdo** [comment]
Thanks for hanging in there. Sorry it took so long. <3
