### ISSUE TITLE
Semantics and classes vs mix-ins - where do you stand?

### ISSUE THREAD

**Issue by EthanEriksen** [mdo/ama#171]
This is something I've been considering for a while now, really ever since I got serious about writing HTML and CSS. To use Bootstrap as an example, using `.col-sm-4` in an HTML file vs. creating a semantic class and using `@include make-sm-column(4)` in an SCSS file.

On one hand a semantic code base has a lot of advantages. You can easily change the style of your site using pure CSS without having to edit the HTML or invalidate class names. However, it defeats some of the reusability of CSS and mix-ins tend to increase file size. But having a ton of classes on each element can become difficult to maintain.

Where do you stand on this? Do you prefer to use mixins or do you like to include several classes with your elements? How is this impacted by your vision of CSS being component-based?

**Comment by mdo** [comment]
I use both to varying degrees. There's no perfect answer for every use case. I try to keep the number of required classes for an element low though. Your specific approach largely depends on your or your team's preferences. A good mix of single-purpose utility classes is pretty helpful though. And if you're building CSS for others to re-use, mixins are definitely helpful in many instances.
