### ISSUE TITLE
jQuerySF talk

### ISSUE THREAD

**Issue by iffyuva** [mdo/ama#173]
hey @mdo great talk: https://www.youtube.com/watch?v=Tjwm9yPzBGg&feature=youtu.be&t=6h26m36s
was going through it after you shared it in bootstrap slack room. i have couple of questions regarding last slide:

last slide mentions:
- linters and validators
- CI tools with github
- Grunt and Gulp
- Stats and reporting

can you please list them out for 1, 2 and 4, (along with links if possible)? thanks.

EDIT: i said you shared the talk link in github, whereas you shared it in bootstrap slack room.

**Comment by cvrebert** [comment]
I'm not @mdo, but:
- linters and validators
  - Bootstrap HTML linter: https://github.com/twbs/bootlint
  - HTML validation GitHub issue bot: https://github.com/cvrebert/lmvtfy
  - HTML validator: https://github.com/validator/validator
  - CSS validator: https://jigsaw.w3.org/css-validator/
- CI tools with github
  - https://travis-ci.org
  - Tool that fails the build if a CSS class isn't used anywhere in the HTML or if the HTML references a nonexistent CSS class; (not public / open-source)
- Stats and reporting
  - https://github.com/katiefenn/parker
  - rake task that reports the number of CSS selectors, file size, and gzipped file size for each CSS file; (not public / open-source)
  - http://cssstats.com/ (seems to be offline at the moment)
    - https://github.com/cssstats
  - tools that graphs CSS file size and number of CSS selectors over time; (not public / open-source)

**Comment by mdo** [comment]
Wow, totally forgot about this issue—sorry! @cvrebert nailed it though. <3

**Comment by iffyuva** [comment]
@cvrebert @mdo thanks for listing out these tools :)
