### ISSUE TITLE
How can I learn CSS?

### ISSUE THREAD

**Issue by collegeimprovements** [mdo/ama#174]
How you learnt CSS? How can I learn enough CSS with basic concepts so that I can apply them well!
Just like your best-practices guide.
You are my ideal and I want to be as prolific as you.

**Comment by mdo** [comment]
I started teaching myself over 15 years ago by copy-pasting examples, tearing things apart and remaking them, and then experimenting with as much as I could. The guides and tips I offer folks these days comes from years of doing that _and_ building systems for larger sites and applications (like Bootstrap, Twitter, GitHub). I guess what I'm trying to say is just keep building things.

Build things over and over again, tear them down and try them different ways. See what others are doing and try to reproduce it with your own twists. Nothing beats that kind of experience.

**Comment by collegeimprovements** [comment]
Thanks :) You are the man.

**Comment by mr21** [comment]
@collegeimprovements, hi :)
To do what you want I propose you to watch and understand a page I made: [mr21.github.io/learncss](https://mr21.github.io/learncss/), I hope you'll understand what offers all the CSS's selector.
There is no text, only interactive examples.

cheers :)

**Comment by collegeimprovements** [comment]
Thanks :) It's good. Will you add advanced topics overtime?

**Comment by mr21** [comment]
Hmm did you mean others examples like "div > :empty" etc.?

**Comment by collegeimprovements** [comment]
yes :+1:  Aside: I just came to know about it.
