### ISSUE TITLE
Validate or check Bootstrap site

### ISSUE THREAD

**Issue by yasirzia** [mdo/ama#179]
How can i validate bootstrap site? like this: https://validator.w3.org/ is there any tool or any plan in future?

**Comment by mdo** [comment]
Sure, you can use that. We have our own HTML validator we run on our docs, though we don't validate our CSS.

**Comment by yasirzia** [comment]
you did not get me. i am asking to you if i purchase an html template which is developed on bootstrap, but i want to know that before purchasing that is this template use right bootstrap classes or all elements. So how can i do this?

**Comment by mdo** [comment]
Unsure. You can try something like Bootlint if you wish, but there's not easy-to-use hosted solution for what you're asking. You'll just have to compare yourself or point me to the template you're referring to.

**Comment by hnrch02** [comment]
There is an unofficial online version of Bootlint at http://www.bootlint.com/.
