### ISSUE TITLE
Creating different modules based on Bootstrap

### ISSUE THREAD

**Issue by reardestani** [mdo/ama#180]
Hi,

I am creating different modules based on Bootstrap but I am stuck in defining custom classes for customizing components. Lets take an example:

I use media objects for creating features list in an **introduction** module like below:
**introduction** is shortened as **i**
**media** is shortened as **m** from 2nd declaration on.

```
<div class="i-features-list">
  <div class="i-media media">
    <a class="media-left" href="#">
      <img class="i-m-object media-object" data-src="holder.js/64x64" alt="Generic placeholder image">
    </a>
    <div class="i-m-body media-body">
      <h4 class="i-m-heading media-heading">Media heading</h4>
      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
  </div>
</div>
```

As you see I have defined a namespace first and then I have defined a custom class for every object so I can style it without nesting rules. The CSS (SCSS) would be like:

```
i-features-list {}
i-media {}
i-m-object {}
i-m-body {}
...
```

In your idea, is this a good convention? or I should only define `i-media` (without defining many custom classes) and use nested CSS (SCSS) rules like:

```
i-features-list {}
i-media {
  .media-object {}
  .media-body {}
  ..
}
```

Please guild me to find a good convention because in this project there are about 180 different modules.

Looking forward to your response

**Comment by mdo** [comment]
Whatever works for your team, though I'd steer away from adding increasingly vague abbreviations for things. We struggle with that at GitHub and Bootstrap, too, and have yet to find the perfect balance. You'll likely end up with a split of new classes and some nested, and that's okay. Try it a few times and see what feels right after putting a component or two to the test, then run with what works for you.
