### ISSUE TITLE
Hyde Theme Question

### ISSUE THREAD

**Issue by michaelportal** [mdo/ama#181]
I messaged you on twitter but I think this might be a better avenue (maybe?). 

I am currently using and modifying your Hyde theme for Github Pages / Jekyll static sites.  One problem that I keep running into is that if the window is too small the nav column on the left will not load properly:  in a smaller window the menu navs will get cut off without the option to scroll down on the left (colored) column to see what is missing.

Is there any solution?

Thank you so much for a fantastic theme! - MP

**Comment by michaelportal** [comment]
Would love to get some help on this!  Thanks!! MP

**Comment by mdo** [comment]
Unsure exactly what you're running into, but the Hyde theme is designed to stack on mobile views. The side appears first and pushed down the content.

**Comment by michaelportal** [comment]
Ah, thanks for getting back to me! I am not talking about mobile views, I am experiencing the problem on this computer for example.  When you open up the site with the browser at a full window size, then there is no problem.  However if you open the site in a smaller browser window (or pull up and make the browser smaller) the nav bar will be cut off and you can use all of it.

**Comment by michaelportal** [comment]
![screen shot 2015-09-16 at 6 20 04 pm](https://cloud.githubusercontent.com/assets/12556918/9910923/d41e19b6-5c9f-11e5-81cd-f34a7e4e3d7d.png)

Here you can see how the page is expect to show up

![screen shot 2015-09-16 at 6 20 10 pm](https://cloud.githubusercontent.com/assets/12556918/9910866/9807d11a-5c9f-11e5-8437-b93a9707bcc8.png)

If someone has a smaller screen or smaller browser window then part of the text is cut off and you cant scroll.  In this second image Hyde is cut off. Since I want to have my stuff pinned to the top of the column, it is usually my nav bar.  

Hope that provides more context.

**Comment by mdo** [comment]
Oh on the sidenav yeah. I'd need to adjust the media queries to account for that and rearrange the content earlier. Can you open an issue with those screenshots on the https://github.com/poole/hyde repo?

**Comment by michaelportal** [comment]
Did it! Sorry for posting it here!

**Comment by mdo** [comment]
Thanks! <3
