### ISSUE TITLE
Found your name on a Tandberg Codec camera control JS

### ISSUE THREAD

**Issue by pestone** [mdo/ama#184]
Hi Mark.

I'm writing because I saw your name in the credits being involved with writing the camera control code for the Tandberg PrecisionHD cams from within one of the C Series codecs. My question was if this code was available somehow OUTSIDE of the codec environment and say, somehow applied to a local server with the intention of say controlling cameras that are ideally hooked up directly to an ethernet connection.

I haven't placed one on wireshark yet (my next to-do) and I've heard they are not DHCP happy nor have any ethernet smarts, but in development I was wondering if you had a system in place to control them in such a manner?

My next attempt is to get an Serial over Ethernet device, create a proper VISCA compliant Serial-to-RJ45 cable and see if I can control them with standard SONY VISCA software over the web.

Peter
pestone@cisco.com

**Comment by mdo** [comment]
Sorry, but I can't help you I'm afraid. I'm assuming whatever tool you're using includes an open source project, likely Bootstrap or something similar.

Best of luck getting the help you need, and apologies again you were led to a dead end here <3.

**Comment by pestone** [comment]
Ahhh. Sadness but yea, probably what it was:
- frontend/styles/vega-bootstrap.scss */
- /*!
-  \* Bootstrap v2.3.2
-  *
-  \* Copyright 2012 Twitter, Inc
-  \* Licensed under the Apache License v2.0
-  \* http://www.apache.org/licenses/LICENSE-2.0
-  *
-  \* Designed and built with all the love in the world @twitter by @mdo and
  @fat.
-  */
  And so you and @fat are forever immortalized :D
  Carry on!

Peter

## 

  PETER STONE ­ IT TECH | NETWORKING | DJ/VJ  http://www.cyberden.com

From:  Mark Otto notifications@github.com
Reply-To:  mdo/ama 
<reply+009ee55db6473a34b2085c7549e579aab0377a2855da0e4792cf00000001120f93569
2a169ce06588bba@reply.github.com>
Date:  Tuesday, September 15, 2015 at 1:05 AM
To:  mdo/ama ama@noreply.github.com
Cc:  Peter Stone pstone@cyberden.com
Subject:  Re: [ama] Found your name on a Tandberg Codec camera control JS
(#184)

Sorry, but I can't help you I'm afraid. I'm assuming whatever tool you're
using includes an open source project, likely Bootstrap or something
similar.

Best of luck getting th help you need, and apologies again you were led to a
dead end here <3.


Reply to this email directly or view it on GitHub
https://github.com/mdo/ama/issues/184#issuecomment-140315066 .
