### ISSUE TITLE
Trouble passing CSS to posts in Jekyll

### ISSUE THREAD

**Issue by gabedeko** [mdo/ama#185]
Hey Mark,

I have been playing around with Jekyll for a couple of weeks now. I really like the way it works and how simple it makes creating a blog so I've decided to update my personal website via Jekyll. My main index page is exactly how I want it to be in terms of styling but I'm having issues styling my posts and my pages. I've looked all over the web and throughout my files and folders trying to figure out how to style my posts but I'm not exactly sure where or how it's supposed to be done. Now my posts have no styling whatsoever. Would you be able to point me in the right direction? I would really appreciate it.

Thanks,

Gabe

**Comment by mdo** [comment]
You're probably running into `baseurl` problems causing your URLs for those stylesheet links to be inaccurate. Read through https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/ and the Jekyll docs for that config option.
