### ISSUE TITLE
Your opinion on this feature request?

### ISSUE THREAD

**Issue by sanspace** [mdo/ama#187]
https://github.com/twbs/bootstrap/issues/17672

Consider it very low priority. :)

**Comment by mdo** [comment]
As my contributor @cvrebert mentions, it's just not possible in CSS to do `Capital Case` like that, and as such not something we'd try to provide in Bootstrap.

**Comment by sanspace** [comment]
Thank you. That was quick. I thought it might take a while for you to
answer in AMA. :)

**Comment by mdo** [comment]
Sometimes it does but for the quick questions like this I try to knock em out fast :).
