### ISSUE TITLE
Prioritizing/Organizing Issues on GitHub?

### ISSUE THREAD

**Issue by marcelosomers** [mdo/ama#191]
I enjoyed your post about how you manage features in Bootstrap. I was curious both on Bootstrap or at GitHub if you guys have a preferred method for managing work on issues. Basically what most other companies might use Trello/JIRA/Pivotal Tracker/etc. for prioritizing,planning, and assigning work and progress toward milestones. I know tools like [Huboard](https://huboard.com) have popped up, but it seems odd to throw more tools to solve this problem.

As a side question (and possibly related to the above question): When you open a PR like your v4-dev one (https://github.com/twbs/bootstrap/tree/v4-dev), is there any way to open the PR before any code gets committed to the new branch? I swear I'd heard talks from you, Joel Glovier, and Zach Holman that said this was your workflow at GitHub, and you could start checklists, discussions, etc. before any code gets committed.

**Comment by mdo** [comment]
Individual product teams use a mix of things here at GitHub—Pivotal and Trello mostly. Bootstrap has nothing fancy—there are far too few people for that. We just rely on Issues itself.

> is there any way to open the PR before any code gets committed to the new branch?

Not exactly. What folks do there is open **super** early PRs where they change just a few things and outline everything else via checklists and what not. Most things start this way—with unfinished work being pushed to PRs with plenty of todos outlined.
