### ISSUE TITLE
Product Designer 

### ISSUE THREAD

**Issue by CrandellWS** [mdo/ama#193]
Not sure if I qualify for the job but it would be an honor to be part of the GitHub team. Can you help me present my best side if you think I would qualify for the job? 

Currently, working towards a Nanodegree sponsorship for the "Full Stack Developer" program. I am pretty new to Python programming so I have started working on the [intro to programing curriculum](https://github.com/CrandellWS/Udacity-Nanodegree/tree/master/Programming%20Foundations%20with%20Python).

**Comment by mdo** [comment]
[The job post](https://jobs.github.com/positions/cec0b09e-5590-11e4-9b36-8b1b5efc4d04) has all the relevant details on requirements and skills we're looking for, so I'd suggest starting there to get a ball park. We're looking for folks who have experience designing interfaces for awesome products. There's some engineering experience we'd like folks to have, but it's definitely geared more towards product and interface design.
