### ISSUE TITLE
Bootstrap 4 blog post + Tether link love?

### ISSUE THREAD

**Issue by hbradley** [mdo/ama#197]
Hey Mark, I'm on the engineering team at HubSpot and it's awesome you're using Tether- made our day. I was wondering if you'd be up for linking to http://github.hubspot.com/tether/ in this post http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/ ?

**Comment by cvrebert** [comment]
Done: https://github.com/twbs/bootstrap-blog/commit/749569f8f7db149dfed7cfbaeeccfca789f4badc

**Comment by hbradley** [comment]
Thanks a bunch!

**Comment by mdo** [comment]
Woot. Sorry for missing this <3.
