### ISSUE TITLE
for 'themes.getbootstrap.com' payments

### ISSUE THREAD

**Issue by KwakYeongCheol** [mdo/ama#198]
Hi, can you help me?

I tried buy a bootstrap themes in `http://themes.getbootstrap.com`

in `credit card info` pages, I tried 5 times for `complete order`.

and then website tell me `zipcode is not valid. blah blah` error message

but money out from my credit card. help me

( $99, $1, $1, $1, $1 )

**Comment by mdo** [comment]
Please email `themes@getbootstrap.com` for specific Themes questions.
