### ISSUE TITLE
Bootstrap research

### ISSUE THREAD

**Issue by eduard9x** [mdo/ama#200]
Hi,
My name is Eduard, I'm doing a research about Bootstrap on the code of conduct and ethical issues that you might have encountered working on it. Also about intellectual property, data protection and any other legal constraints that might apply to your open source project.
I have lots of general information, but nothing specific to Bootstrap. I thought it is good to ask the creators about it. 
Sorry to message you on Twitter as well. I just found this repository, so I thought it might be better place to ask. Let me know if you can help me with anything in my list. I can give you more details about it if you need any.
Thank you !

**Comment by eduard9x** [comment]
Hi again,

I was thinking to clarify some of the stuff. I'm just doing a research for a presentation at Uni. I'm not interested in gossip or other stuff. I'm looking for positive examples from your team.

My team is researching about your open source software. I am focusing on ethics.
Ethics is about good and bad, legal vs moral. So although it is legal not to clean your desk, people do that. Or maybe you have a code of ethics regarding the code writing: how to write code so that everyone could understand what someone did there. Adding comments, indentation, etc

Also we research on the legal aspects of this software as well. Has anyone tried to use your product under a different name, deleting your license and claiming it's their own product ? If that happened, what did you do ? Else, what would you do if that would happen ? (if-else Geeky joke haha) 
Which means of detecting that are you using? How do you protect your software? Were there any situations of data being disclosed?

Obviously you are all professionals, you probably don't need a code of conduct/ethics or others related to that. Or maybe you all work under the BCS code of conduct. I don't know, but it would be a great help if you could let me know a couple of stuff about it.

Thank you,
Eduard

**Comment by mdo** [comment]
Sorry I never got back to this. Not sure how much I can really comment on these things. We've run into things from time to time, but nothing major that'd feel worth covering here.

**Comment by eduard9x** [comment]
Hi,

Me and my team managed to finish our research and deliver a presentation about Bootstrap.
It went good. Too bad we haven't got the chance to give some real life examples.
We managed to talk about general stuff and give examples from other companies.
Thank you for replying after all. It was a long shot but I had to try :)

Besides this I'm just curious if you have any available opportunities at Bootstrap for students.
I'm based in London. Might not be close to you, but I have a laptop, so I could help with small things.
Please let me know at your earliest convenience if my skills can be of any use for you and your team.
