### ISSUE TITLE
Bootstrap API definition

### ISSUE THREAD

**Issue by joerideg** [mdo/ama#202]
Hi Mark,

Currently at my company we are working hard to create a central project for front-end code to live. This project will be pulled in via bower/npm3 into other projects that will use it to style and compose their UI. Basicly its a custom bootstrap plus angular directives. One thing we have trouble with is defining a good API. I was wondering how Bootstrap exactly defines its API. Is it just the css classnames, or als for example the css order and the properties? How do you deal with improving Bootstrap as a library while staying backwards compatible in minor versions?

Looking forward to your reply!

**Comment by mdo** [comment]
Class names, mostly, yeah. Our decently strict versioning policy keeps us on track for what makes it's way into minor releases vs major ones. We bail on backward compatibility in major versions to clean house, so as long as that kind of stuff is clear, I don't see it as a huge issue (internal or external).

**Comment by joerideg** [comment]
Thanks!
