### ISSUE TITLE
So speaking of the forever upcoming v4...

### ISSUE THREAD

**Issue by john** [mdo/ama#204]
Hi Mark, I'm working on a side project which I'd love to use as a testbed for v4. Any ballpark on when the next release might drop?

**Comment by john** [comment]
Just joined the Slack channel and saw that this is asked 3x per day. Feel free to close if that's the appropriate channel for this question :-)

**Comment by mdo** [comment]
Should have another alpha release out soon :). Been a busy few months for us, sorry <3.
