### ISSUE TITLE
Few personal questions

### ISSUE THREAD

**Issue by gauravmak** [mdo/ama#206]
1) After hours of work, what do you do to relax/refresh? (Or there is never any need like that? ;) )

2) What is the primary source of income for the experts like you who invest most of their productive time in open source projects? (Self-satisfaction and Passion to create is more than money I know)

3) Related to the question above - Why should one put an idea into an open source project instead of cashing in by selling it? I feel there must be very compelling reasons for the same. Wanna know them to inspire myself and contribute more to the open source projects.

Thank you.

**Comment by mdo** [comment]
1. When not working, I play a decent amount of video games—mostly Fallout 4 and Minecraft lately :). Also spend time with the girlfriend and dog.
2. I have a full-time job as Director of Design at GitHub, so open source isn't my primary source of income. However we do earn a bit off ads on Bootstrap's documentation, as well as our new side business, Bootstrap Themes.
3. If there's not a strong reason—financially, organizationally, etc—to **not** open source it, I say open source it. As we do with Bootstrap (our ads and themes), there's plenty of opportunity to earn money off additional projects on top of open source. I don't think Bootstrap would be as huge as it is today had we charged money for it, and by getting it in more hands we open the door for ourselves and the community to make money off the project.

Hope that helps!

**Comment by gauravmak** [comment]
Thank you so much for the answers. Appreciable.
It solved most of my queries regarding the reason for popularity of open source language frameworks and other projects as well. Best wishes. Bye.
