### ISSUE TITLE
Tips for open source projects

### ISSUE THREAD

**Issue by cjpatoilo** [mdo/ama#209]
Hi @mdo

This is my first time with open source project. I wanted any tips or improvement, that this type of project can not fail to have.

Well, two weeks ago I began to devote a little more of my free time to share a personal project. Of course, this project did not have all the features that it currently has, not even a concern with other forms of distribution. I was honing and improving each feature one by one during those days, while analyzing the way they were implemented in other projects.

This experience has been fascinating. I learned much more than I expected. And that phrase was the inspiration for all these days:

> _“Even if people say — don’t reinventing — I think it should be reinvented, because it will teach you something. So even if there is already something out there, dive into their code, and perhaps rewrite everything, even if it’s just to learn.“_

Well, here’s one more CSS framework. https://github.com/milligram/milligram

But as I said, this is my first time with open source projects and I still have some doubts. I know there's a lot to improve.

**Comment by davidschoi** [comment]
Milligram looks pretty sweet. Good job! :)

**Comment by cjpatoilo** [comment]
Thanks @davidgumzchoi <3
