### ISSUE TITLE
Breaking styles into individual components

### ISSUE THREAD

**Issue by alokpant** [mdo/ama#211]
I have been trying to find a maintainable, scalable way of writing CSS. This has lead me to alot of CSS techniques like BEM, OOCSS and others. While all these techniques have their own good and bad side, I have not yet come to a better way of writing CSS. So I started writing something which would make sense to me. So basically here's how it would look.

Previous:

```
<h3 class="header-h3">I am header</h3>

.header-h3 {
   font-size: 1.5em;
   color: black;
   text-transform: uppercase;
   padding: 0px 30px;
   margin: 0;
}
```

Would be:

```
<h3 class="font-size-24 txt-clr-black txt-uppercase padding-left-30 padding-right-30 margin-0">I am header</h3>


.font-size-24 { font-size: 1.5em; }
.txt-clr-black { color: black; }
.txt-uppercase { text-transform:  uppercase; }
.padding-left-30 { padding-left: 30px; }
.padding-right-30 { padding-right: 30px; }
.margin-0 { margin: 0; }
```

You can image, the class based system would look pretty messed up when on views the source as all of these classes have to be repeated if there are 5 h3 elements. But it is easy to maintain. If I want to add another property say h3 has underline. Then I can just add .text-underline class to the element. LOC is also minimized as I don't have to keep adding repeated things in CSS.

What do you think about this technique?

**Comment by mdo** [comment]
A bit too far in one direction for my taste, but some folks like it. Check out Bass CSS and Tachyons for more stuff like that :).
