### ISSUE TITLE
Question about work

### ISSUE THREAD

**Issue by theviajero** [mdo/ama#213]
Hi Mark!,

As an entry level developer in a "third" country world is hard to a decent job (Decent salary) in here. Do you think that I can get something if I offer to work remotely for free, like in a "trial period"?...  I will add something that describe me better. 

https://sysdev.co/blog/posts/why-i-began-with-this-never-forget/

Sorry if this is not the place for ask this.

**Comment by konekoya** [comment]
Broken link?

**Comment by theviajero** [comment]
@konekoya  No... Why?

**Comment by konekoya** [comment]
not quite sure, but I cannot open that page with Chrome..

**Comment by theviajero** [comment]
Mmm  Very rare... Do you try just sysdev.co   ? I can open it perfectly.

**Comment by konekoya** [comment]
I think that's my network problem, I can open it with mobile phone. Sorry about that

**Comment by theviajero** [comment]
No problem. If you can, give me your opinion. 

Greetings!

**Comment by mdo** [comment]
Giving yourself up by working for free, even for a trial, doesn't help anyone. If you're capable of doing great work, you should be earning the money for it. That's probably not super helpful as I have no idea what your entire situation is, but doing spec work makes you look bad and you're not getting paid.

I'd suggest trying to drum up work with open source projects, example case studies, etc to demonstrate what you can do. That kind of approach, while similar in you're doing "free work" in both examples, is more useful to you than selling yourself so short with free professional work.

Hope that helps some!
