### ISSUE TITLE
GitHub label usage 

### ISSUE THREAD

**Issue by pevers** [mdo/ama#214]
Hi @mdo,

We are students doing a small research on GitHub label usage on pull requests mainly for large open source projects. Previously we have looked into Docker and found that they have integrated the Kanban method into their workflow by using custom GitHub labels. Bootstrap is an awesome project and we have a couple of small questions about the workflow and we would be really happy if you could answer them. 

We see that Bootstrap is actively using labels, but there is not really a workflow in the labels on pull requests, e.g. a pull request is listed as 'css' or 'v4' but not as 'staging', 'code-review' etc. Are you using ZenHub or something internally to manage pull requests? Or is there no strict policy on merging pull requests? We are curious because in such a large project with new pull requests every day it could be hard to manage and process all of them.

Cheers,

Peter

**Comment by mdo** [comment]
> Are you using ZenHub or something internally to manage pull requests?

Nope, just GitHub's issue/pulls tracker.

> Or is there no strict policy on merging pull requests?

For most small to medium sized things, anyone on our core team can and does merge PRs. For things that are a bit more involved, include design/aesthetic changes, or key JS behaviors, myself or one other person are the ones to merge.

> We are curious because in such a large project with new pull requests every day it could be hard to manage and process all of them.

Definitely not easy :D. Takes a lot of time, and the amount of time I've been able to put into it has diminished over the last year. Sucks super hard, but the struggle to find time to work on stuff is part of the fun I think :).

**Comment by pevers** [comment]
Thanks for making time to answer our questions! Much appreciated.

Cheers and keep up the good work!
