### ISSUE TITLE
Question on bootstrap issue #17093.

### ISSUE THREAD

**Issue by graiz** [mdo/ama#215]
You closed issue https://github.com/twbs/bootstrap/issues/17093 on bootstrap (hamburgers)  that I had opened saying that the issue was not specifically actionable. I'd love to chat with you to discuss how a solution could be actionable. 

I think bootstrap should advance the state-of-the-art, not just in its use of CSS patterns but also regarding UI patterns and improved usability. 

My email is graiz@raizlabs.com; I'd love to understand your position and perhaps better to explain my own. 
- Greg

**Comment by mdo** [comment]
Hey there, sorry for the late reply. It's been awhile since I looked at that issue, but the gist of it is that we're not making any other big changes to v4 (hopefully haha). The nav we have in there now is what we'll launch with for v4. We can look at other options, but we also don't want to go try to solve every nav situation we could imagine. I do want the best design and code we can get though, so keep feedback coming in if you're up for it :).

**Comment by graiz** [comment]
Happy to keep the feedback coming but I'd love someone on the tech team to
partner with to get feedback/ideas implemented.  I've done platform design
in the past and getting usability patterns right is super critical because
those patterns are replicated over and over again.

If you or another developer on the project is interested in usability
improvements to the platform, I'd love to connect and describe some of the
issues.

## 

_Gregory Raiz, Founder CEO_

Mobile Strategy, Design & Development

www.raizlabs.com | Check my calendar
https://www.google.com/calendar/embed?src=graiz@raizlabs.com&ctz=America/New_York&mode=WEEK
 | @graiz http://www.twitter.com/graiz | 617-286-6101
[image: Raizlabs]

**Comment by mdo** [comment]
I'm the creator and maintainer, so I'd be the one to talk to :). I'm fully aware of the usability concerns around the hamburger menus, too, for what it's worth. Moving away from that isn't likely to happen in v4, but I'm looking forward to figuring out how we can enable other custom nav patterns.

**Comment by graiz** [comment]
I explored the idea a little further... I would love your support to make
this a reality in Bootstrap...

http://www.raizlabs.com/graiz/2016/05/06/no-more-hamburger-menus-introducing-the-hot-dog-menu/

Comments and feedback welcomed.
