### ISSUE TITLE
How to `<nav>`?

### ISSUE THREAD

**Issue by rafaelrinaldi** [mdo/ama#216]
I've noticed that in most of your projects you don't actually use lists inside your `<nav>` tags, you just stack anchors on top of each other. I was just wondering if there's any specific reason for that?

**Comment by mdo** [comment]
It's semantic and more compact. I've been shying away from having to restyle entire `<ul>`s just for inline navigation and running with `<nav>` instead. It's simpler and accomplishes the job just as well nearly every time (except for say like dropdowns in Bootstrap which need a wrapping element around the anchors).
