### ISSUE TITLE
styleguides and position properties

### ISSUE THREAD

**Issue by vlrprbttst** [mdo/ama#218]
I've been studying and trying to create a living styleguide system to use and integrate on my next big work project and one specific question fills me with doubts:

**does a styleguide define only the appearance and behaviour of a component, but not its positioning?**

Say for example we have a button and that same button has multiple positioning and multiple different margins across the website. how do you deal with that? does that become a new "template" each time, for example, if its positioning varies from static to absolute? or do you rely on additional classes for positioning?

should you create another level of positioning in the styleguide or just go with the flow according to the specific page need for that button?

thanks! :smile:

**Comment by mdo** [comment]
Layout and spacing is usually up for grabs. I don't specify that stuff as part of say the button, but rather punt that to a layouts, templates, or meta components section. For example, you might have a button and a larger `.form-actions` like here on GitHub where multiple buttons are spaced apart and aligned differently than by default.
