### ISSUE TITLE
What do you think about flexible.gs ?

### ISSUE THREAD

**Issue by dnomak** [mdo/ama#220]
I never learned thoughts :)  I would be glad if you examine ? 

https://github.com/flexiblegs/flexiblegs-scss-plus/blob/master/flexiblegs-settings.scss

My english is really bad. I'm sorry for it :(

:heart:

**Comment by mdo** [comment]
Super late reply, but I've never used it, so I can't comment much on it. Looks interesting though!

**Comment by dnomak** [comment]
thank you :heart_eyes:
