### ISSUE TITLE
New to Web Development 

### ISSUE THREAD

**Issue by fermon-205** [mdo/ama#221]
Hi my name is Fermon Grays, I'm new to Web Development- I've been developing in Java for a number of years. I'm aware that your probably extremely busy Mark O, but I wanted to know if possible if i could chat with you some time. I've been following you on the internet & I'm very interested in your work & learning Bootstrap & other Web technologies?

Thanks

**Comment by mdo** [comment]
Sorry for the late reply! Feel free to ask anything here or shoot me an email and I can try to find time to reply to specific questions :).
