### ISSUE TITLE
The longest stuck you ever had?

### ISSUE THREAD

**Issue by sukrosono** [mdo/ama#222]
Hey dude, i really curious what's your longest stuck when you wanna build something.
lately i had almost 2 weeks stuck, i am just reading random stuff, till it solved.

**Comment by mdo** [comment]
Not sure how to answer that honestly. I've noodled on stuff for awhile, but I try my best to not get too bogged down in it and move on to something else until I can come back to it with fresh eyes. Give that a try and see if it helps.
