### ISSUE TITLE
using bootstrap-4-alpha

### ISSUE THREAD

**Issue by fahimfkamal** [mdo/ama#223]
Is bootstrap-4-alpha ready for use? I am a beginner in bootstrap. I make a project using bootstrap. Can i use bootstrap 4? can bootstrap 4 support [http://kybarg.github.io/bootstrap-dropdown-hover/index.html](http://kybarg.github.io/bootstrap-dropdown-hover/index.html) type of animated dropdown?

**Comment by ghost** [comment]
Hi, Mark. Similar question. I would like to know when Bootstrap 4 will be released as a stable version? Thanks.

**Comment by mdo** [comment]
No date. Yes, you can, but it is alpha—classes and features will change until we go beta. Hover dropdowns are not supported, and we won't be adding those kinds of animations (though some kind of animation could be cool).

**Comment by davidak** [comment]
@mdo when do you expect a beta release? it's a half year since the alpha-2.
