### ISSUE TITLE
Jekyll Assets

### ISSUE THREAD

**Issue by asomervell** [mdo/ama#226]
Gidday, if I have a quick dig... would it be fair to say you prefer minibundle when you're building static assets in jekyll for the bootstrap v4 site? [edit nope, seems jekyll-assets would give a similar filename]

Also, bought the startup theme— its pretty cool — but I expected it to be built in v4! :bomb:  can't seem to get anything compiling less in Jekyll effectively :-1: 

Thanks!

**Comment by mdo** [comment]
I don't use any Jekyll plugins for asset management. On the CSS side, it has the Sass compiler built in and can minified things easily enough. And yeah, themes for v4 are coming as soon as we finalize v4 itself (it's still alpha). You could look into using some build tools like Grunt or Gulp to do the compiling for you though.
