### ISSUE TITLE
Any plans to build Conditional Loading or JS Adaptive solutions into Bootstrap?

### ISSUE THREAD

**Issue by WebMagi** [mdo/ama#227]
Bootstrap is great for building RWD sites, but what about performance? Delivering the same code base across all screens makes development and upkeep a cinch, but may not provide an optimal user experience on mobile in terms of page load times. What about Conditional Loading or JavaScript Adaptive solutions? Could these or some other solutions be utilized within the framework to help bring performance to the forefront?

There's a lot of vitriol spewing in some communities by coders who feel that Bootstrap is bloated and far from ideal for developing responsive sites. Case in point: 
1: [Discussion 1](https://forums.adobe.com/thread/2123590)
2: [Discussion 2](https://forums.adobe.com/thread/1975068)

Will version 4 address some of these concerns, or do you feel they are misguided?

**Comment by mdo** [comment]
Probably not something I can help with (I don't write JS), nor that I see Bootstrap doing anytime soon, so I can't really say if it'd be helpful or misguided :).

**Comment by WebMagi** [comment]
Should I have asked this question somewhere else, maybe here perhaps?: [twbs/bootstrap
](https://github.com/twbs/bootstrap/issues)

**Comment by cvrebert** [comment]
> What about Conditional Loading or JavaScript Adaptive solutions?

I'm not an expert in those, but FWICT, to my naive self, it seems like that could be done generically with some extra tooling that just reads the media queries in Bootstrap's generated CSS and generates other CSS files split by applicable media query (and corresponding JS to load/toggle between the CSS files). Doesn't sound like any first-party integration is necessarily required, and it's a fairly advanced technique that IMHO would go beyond the needs/abilities of many of our users. It's something that might be neat to mention in the docs though.

As for stuff like HTTP Client Hints and varying the HTML served to the browser, that necessarily involves the server-side backend, and thus is beyond Bootstrap's purview (which is the frontend). But again, this is something which might be nice to mention in the docs.

**Comment by WebMagi** [comment]
Search Google Books for "[High Performance Responsive Design](https://www.google.com/search?tbm=bks&q=High+Performance+Responsive+Design)", Tom Barker, page 95 - Lazy Loading content when it's actually needed. (Guy Podjarny - another good read)

I'm not saying you guys should figure out how to incorporate any specific techniques/options into your framework, but surely you get it that performance is important to every single user you have. Mobile first doesn't mean anything if mobile devices are downloading content they don't need by default; the same content as desktops.

**Comment by cvrebert** [comment]
So, with regard to the framework lazy-loading user content, the only instance that comes to mind is our Carousel widget. Lazy loading the slide images would indeed be a useful addition, provided the code isn't too complex.

With regard to lazy-loading the framework itself, I sketched how that might work for CSS in my previous comment. For lazy-loading the framework's JS, once we get ES6 modularization fully working in Bootstrap v4, it seems like folks should be able to apply generic tooling (e.g. AMD/requirejs, SystemJS) to load specific modules at the particular time they become necessary, as opposed to loading those modules at initial-page-load-time (although the perf trade-off between the size and number of HTTP requests complicates things).
