### ISSUE TITLE
my site enio.it

### ISSUE THREAD

**Issue by oine** [mdo/ama#229]
Hello Mark, I am a self-taught, I need help but Adrian does not respond to my request for help!
Can you tell me if you can see the icon of whatsapp with the original color green?
On my iPhone do not work on the home page green button (travel, gallery ...) and http://www.enio.it/Photogallery/indice_gallery.html the link does not work on the image.
On the desktop it's all OK! because?
Can you help me rispondendomi by mail, a big hug!

enio.it

**Comment by mdo** [comment]
Hey there, apologies for the late reply, but I can't help with personal projects like that. Hope you found your answers! <3

**Comment by oine** [comment]
thanks for your reply and for your help.

Ciao, ciao.
Inviato da iPhone
Enio +39 366 9945373

**Comment by ghost** [comment]
## now it works!

**Comment by oine** [comment]
No works.
Sorry I difficult to visit your center help, becouse I do not speak very well English!
Please if you possibile send me by mail the new code corret for boutton green ( Home page) to work all and IPhone.

Thanks you!

Inviato da iPhone
Enio +39 366 9945373
