### ISSUE TITLE
How did you improve yourself?

### ISSUE THREAD

**Issue by oguzzkilic** [mdo/ama#230]
How did you improve yourself? What do you recommend for those who want to improve themselves?

**Comment by mdo** [comment]
First, do it again, and again, and again, and again. When I was first learning design and front-end development, I'd try my hand at recreating things, tearing them down, rebuilding them from scratch, extending them, etc.

Second, find someone who can mentor you about the intangibles of design. Mastering tools and workflows is easy, but presenting and articulating and thinking about problems in the right ways takes way more time to master. Simply doing it over and over again doesn't always help with that kind of stuff either.

Hope that helps a bit!
