### ISSUE TITLE
Bootstrap 4 Navbar Dropdowns

### ISSUE THREAD

**Issue by atcraigwatson** [mdo/ama#231]
Hi @mdo, I was just browsing the docs of V4 and fiddling around on codepen then to notice there really isn't any documentation on how to set up a navbar dropdown. 

I have been tweaking a pen to see where it gets to and now have this below:

http://codepen.io/Craig-Watson/pen/wGLebK/

However I thought seen as though I had found myself with a way to contact you I would ask the man himself is this is how he would achieve a responsive collapsing navbar, similar of that from V3 using the V4 framework.

I appreciate you are more than likely quite busy but it really would be great to here your feedback :)

Craig

**Comment by mdo** [comment]
Coming in https://github.com/twbs/bootstrap/pull/19890.
