### ISSUE TITLE
Go to/favourite fonts and colour schemes

### ISSUE THREAD

**Issue by bnjmnt4n** [mdo/ama#232]
Hi! I'm interested to find out what are your favourite fonts/colour schemes that you use most of the time, especially for things like new sites/presentations.

**Comment by mdo** [comment]
[base16](http://chriskempson.github.io/base16/#ocean) has some amazing color schemes. Those are some of my favorites for editors, Terminal, and slides.

Favorite fonts for those kind of things are usually sans-serif—San Francisco, Roboto, Helvetica, etc. I rarely go with anything more stylish or embellished than that these days :).
