### ISSUE TITLE
Automatic Github synchronisation with webserver

### ISSUE THREAD

**Issue by ihebfehri** [mdo/ama#233]
Hi there. 

First of all, thank you for supporting the locals trying to have our way around this Great Wave of Computer Science. 

My issue is, i am trying to automatically synchronise my GitHub with amazon web server:
I would like that my website files would update after a push. 

Would you know if that is possible? 

GitHub have drowned my research with their own web hosting service, so i am having trouble finding a solution to this. 

Help will be greatly appreciated ! Thanks

**Comment by mdo** [comment]
You should be able to accomplish that [with webhooks](https://developer.github.com/webhooks/).
