### ISSUE TITLE
why did you use sass? (instead of less)

### ISSUE THREAD

**Issue by yevgnenll** [mdo/ama#234]
hi @mdo i have a questios why did you decide to use sass?
i've already read you twitter so i agree now
but i wanna know more exact reason
because i have to **persuade** my team

could you reply to me?

**Comment by mdo** [comment]
Community size, speed (Libsass beats Less, but Ruby Sass doesn't), etc.

More than anything else it comes down to personal preference—for the syntax each provides, for the tooling required by both, and the way in which you intend to produce and consume your stylesheets. For example, in Less, every class is a mixin, but not so in Sass.
