### ISSUE TITLE
Thinking behind `.btn-outline-primary` vs `.btn-outline.btn-primary` in Bootstrap v4.

### ISSUE THREAD

**Issue by bjankord** [mdo/ama#237]
Hey Mark,

I was curious what your thinking was behind making the button outline modifiers for different colors their own unique class instead of chaining a modifier for outline and one of the existing color modifiers.

I liked the explanation behind when you update buttons to require a modifier class in Bootstrap. 
https://github.com/twbs/bootstrap/pull/7809
Was hoping to understand the logic behind this update as well.

Thanks!

**Comment by mdo** [comment]
Chaining would just mean more specific selectors that others would have to override for their own customization. Similarly, it muddies up the modifier classes across your project; how do you know if changing `.btn-primary` affects `.btn-outline.btn-primary`, if at all? Doesn't really provide any benefit :).
