### ISSUE TITLE
bootstrap in wordpress

### ISSUE THREAD

**Issue by ste34** [mdo/ama#242]
Hi Mark,

I code a bit, though I'm a near beginner.  May I ask if there's a convenient way to bring the Bootstrap code/libraries into a WordPress website?

I'm wondering: Is there a WP plugin that just does that correctly/automatically?  Or does a person needs to be able to go into the functions.php file of their WP theme, and add the correct lines of code?

I'm really hoping to add some Bootstrap to my WP site, and I've spent some time and haven't quite been able to figure this out.

Thanks very much!
Steve

**Comment by JamesVanWaza** [comment]
@ste34 , did you figure out how to setup wordpress in bootstrap, if not contact me at @jgacuca567.

**Comment by mdo** [comment]
I'm unsure if there's something out there to bring it in for you without additional styles through a theme. I'd consider asking in our Slack maybe.
