### ISSUE TITLE
Curiosity about a possible Summer Design Internship at Github

### ISSUE THREAD

**Issue by priyank1205** [mdo/ama#245]
Hey Mark. Sorry for bothering you, but I was wondering if there could be the possibility of procuring a summer internship at GitHub for User Experience Design (or Product Design). Hoping for a prompt reply. Thanks !

**Comment by mdo** [comment]
Sorry, we don't have any intern positions for this coming summer. I'll tweet out if/when that changes though!

**Comment by priyank1205** [comment]
Thanks for replying !
