### ISSUE TITLE
Github flow

### ISSUE THREAD

**Issue by chhuang** [mdo/ama#250]
In your article on [Github flow](http://markdotto.com/2014/05/02/some-github-flow/), in point 5 (Shipping it), can you expand a little bit on the first bullet point (Branch deploy) please.

How does deploying temporarily to production instead of master work? After you deployed the branch to production, do you merge the branch back to master and then the CI kicks in and deploys again to production? Wouldn't that duplicate the same deploy on production? How does it work?

Appreciate if you can clarify this point for me.
Thanks!

**Comment by mdo** [comment]
Deploying a _branch_ to production allows us an instant rollback option; if things go awry, we can immediately deploy the stable `master` branch. If it's one person deploying their branch and then merging to `master`, we'll wait for CI to run and then redeploy `master` to our production environment.

When we have a queue of people deploying their branches, we basically have rolling branch deploys. We use Hubot in Slack to tee those up (e.g., `.deploy github/branch-name to production`). Hubot steps in to automatically merge in `master` once more, which includes the last deploy's branch. That way we constantly have the latest code in our branch or master on production servers. Usually there are no duplicate deploys in this flow.

Does that help?

**Comment by chhuang** [comment]
Thanks for the clarification Mark! Please correct me if I'm wrong.

After you deployed the branch to production, and then if everything is ok, you merge that branch to master and the redeploy again to production. At that point there is no difference between master and production because that branch is already in production. Why deploy again from master? 

I hope that makes sense.

**Comment by mdo** [comment]
Master is locked and protected, so you always want to err on having that out in production than someone else's branch. Prevents accidental changes, deploys, perf issues, etc. Also ensures that others are unblocked to deploy to production. If a branch is out in production, that's a signal to other engineers that someone else is "using production" and you shouldn't deploy.
