### ISSUE TITLE
What is your Development Environment for Web Developing?

### ISSUE THREAD

**Issue by aradabir007** [mdo/ama#251]
Can you tell me about your development environment for front-end development like which editor do you use? which settings do you use in the editor? etc. I guess you can work in any environment because of the experience you have but I'd still love to hear some advices for setting up a development environment to improve productivity. Thanks :)

**Comment by mdo** [comment]
Most of my setup is detailed in my https://github.com/mdo/config repo. It includes my steps for getting up and running on any new Mac, as well as my preferred plugins and more for Atom. Settings wise for Atom, my font is SF Mono at the default 14px, indent guide is shown, and soft wrap is on. Nothing too crazy :).
