### ISSUE TITLE
Bootstrap 4 - modal

### ISSUE THREAD

**Issue by markostalma** [mdo/ama#256]
Hi Mark,

I have one questions for you about Bootstrap 4 - modal in section Tooltips and popovers. On demo when click on button and popover open can not close modal, even if you turn off the popover or dont click popover button. My question is: Is that a normal for this demo ? I send you a screenshoot in continuation on this message. I hope to hear a response. Excuse for my bad English. Thanks in advance. Bootstrap is awesome! :)

![modal---tooltips-and-popovers](https://cloud.githubusercontent.com/assets/20398135/23697406/eb98578c-03e7-11e7-94a5-56dc2cdbeea4.jpg)

Kindest regards,
Marko Štalmatović
mstalmatovic@gmail.com

**Comment by mdo** [comment]
Bootstrap stuff can be tackled in the Bootstrap repo, thanks!
