### ISSUE TITLE
Entity in question: Facebook. Net positive or negative effect on the world?

### ISSUE THREAD

**Issue by abhikandoi2000** [mdo/ama#257]
Either consciously or subconsciously everyone's familiar that the world is hooked onto Facebook. This puts Facebook in a unique position of affecting the way people think. And the way people think is what governs their actions and hence determines how the future would look like.

Facebook wouldn't be affecting the way people think that much if people only used Facebook for chatting with their close ones. But that's both a good and a bad thing - good because they'd not be exposed to negativity/hatred/racism and bad because they'd miss out on perspectives that contradict their thinking. But chatting is not the only thing that people use Facebook for. They are also exposed to all sorts of events happening in the world. Though for most people, the events that they see are a highly biased (both positive and negative) view of the world.

What do you think about this? Does Facebook have a net positive or net negative effect on the world? And why?

**Comment by mdo** [comment]
Probably not the best person to ask about that :). I barely use it myself, though I don't see it as having an overall negative effect on the world. Definitely has an effect though, perhaps for some groups of folks more so than others.
