### ISSUE TITLE
Removing Bootstrap from the site

### ISSUE THREAD

**Issue by completeonline** [mdo/ama#260]
Hi,

Please excuse my ignorance of the correct wording and what I'm about to ask!

If a developer has used Bootstrap on a site (that he's been paid for) can he easily pull bootstrap from the site without going to the server to render it unusable (page 404 not found)?  I don't know if I've phrased this correctly or if this even makes sense, obviously I'm not a developer :)
As I've never used Bootstrap I'm wondering if it is a 'login' type of thing linked to our site or would he physically have to go into the code on the server and remove Bootstrap?

Thanks for any help at all,

**Comment by mdo** [comment]
Bootstrap is HTML, CSS, and JavaScript—there's no login or interface for you to manage it. You can remove it without causing your pages to 404.

**Comment by completeonline** [comment]
Thanks!
