### ISSUE TITLE
Question about Cards in Bootstrap v4

### ISSUE THREAD

**Issue by ghost** [mdo/ama#261]
Hello, I am trying to create a blog layout using Bootstrap v4. I am wanting to have cards with an image to the left or right of the other content. I was wondering if you had any insight on the best way to implement the classes for .card-img-left and .card-img-right. I've attached a screenshot of a wireframe to give a better sense of what I'm asking. Thanks in advance!

![screen shot 2017-04-18 at 1 48 15 am](https://cloud.githubusercontent.com/assets/20322388/25117984/e8637896-23d9-11e7-8e7e-3dd7a8193a2c.png)

**Comment by mdo** [comment]
Grid system or flexbox utils can help you out here. I can't spend much time crafting something for this right now though—it's a feature request that I believe is already open in the Bootstrap repo. Feel free to ask in our Slack or on StackOverflow.
