### ISSUE TITLE
About the site http://getbootstrap.ru

### ISSUE THREAD

**Issue by patsuckow** [mdo/ama#262]
Hi Mark
At this site http://getbootstrap.ru an inaccurate translation of the English text into Russian has been made. Many orthogaphic errors. Can I help with this somehow? I live in Russia and I am a native speaker of the Russian language. I would like to help you correct these errors. No payment is required.
?

**Comment by sapegin** [comment]
At first I thought that this translation was made with Google Translate but actually Google Translate gives better quality ;-| Are you sure this site is official?

They also have more ads than the official English site ;-)

**Comment by vitkarpov** [comment]
That's how I sound for native English speakers 😆

**Comment by mdo** [comment]
Nothing but the primary, English docs site is official.
