### ISSUE TITLE
Are you interested in collaborations for Bootstrap 4 products?

### ISSUE THREAD

**Issue by alexandru-paduraru** [mdo/ama#265]
Hi Mark,

First of all, thank you for building the Bootstrap framework, it helped us set the base of our business. In this way, we are doing what we love (design) and we don't have to look for other jobs 🙏🏼 

I'm the co-founder of www.creative-tim.com and during the last 3 years, we've built some popular [Freebies](https://www.creative-tim.com/bootstrap-themes/free) based on Bootstrap 3. We've also managed to generate some revenue which was invested back in developing great looking dashboards and UI Kits. We recently launched a Bootstrap 4 UI Kit based on a design [made by Invision](http://demos.creative-tim.com/now-ui-kit/index.html) and it was received very well. We want to give back to the community so we released all our freebies under [MIT License](https://github.com/creativetimofficial/material-kit), in this way the freelancers who cannot afford to buy a design will use our products without any further constraints.

Now we are looking to help more people use high-quality design products. As the creator of Bootstrap, I think you are the right person who can guide us in this journey. There are a lot of people who want to build websites but they cannot afford to pay a good designer $10-15k so, here we come in the game, we give them the quality of that design on a very strong code base, Bootstrap 3/4, for free. I wanted to know if you are interested in any kind of collaborations like showing on the Bootstrap that there are different designs/Free Themes for Bootstrap or having a Premium category or any other ideas that you think will help developers.

BTW, our website's presentation was on [Bootstrap Expo](http://expo.getbootstrap.com/) for almost 2 years, that generated, in the beginning, some revenue which helped us go over the fail path... Don't know if this was made intentionally or the website wasn't updated, thank you for this too :-)

Best,
Alex

**Comment by mdo** [comment]
@alexandru-paduraru Haven't forgotten about this! Just launched our Job board and we're hard at work getting a v4 beta in place. One of us will reach out soon—would love to chat about some ideas we've had!

**Comment by alexandru-paduraru** [comment]
@mdo Glad to know that you take this into consideration. I've just seen the Job Board, 11 posts so far, things are going in the right direction! 

Very curious to see what ideas you have and what we can achieve together. Good luck with the dev of v4 beta, people are waiting for this launch like how they are waiting for the Christmas gifts 😅
