### ISSUE TITLE
What advice you have for an aspiring front end dev?

### ISSUE THREAD

**Issue by sampiecz** [mdo/ama#267]

**Comment by mdo** [comment]
Apologies for the delay in responding, I had my parents in town all last week. I see you've deleted your comment and closed the issue, but I still wanted to share something here.

To be honest, I don't feel I ever learned anything from a design or development book. I own a couple dozen, but I haven't read most of them cover to cover. Hell many of them I've never even opened. I have, however, built a ton of things. My entire experience in becoming a designer/developer has been around seeing something I liked and trying it myself. That often starts with building an exact clone, but once you've done that, you can tweak, adjust, evolve. Do that enough times and you'll start creating your own things from scratch.

I learned HTML and CSS by hand with Notepad 15 years ago. It was the best decision of my life. I never had an autocomplete—I had to learn all the syntax and formatting and bugs. Understanding the languages at that level was paramount for me. Unsure how that carries over to legitimate programming, but that's how I became the developer I am today. Learn by hand, learn by doing.

Hope that helps.

**Comment by sampiecz** [comment]
No worries on the delay!  Thank you so much for answering.  Made my day.  Figured you probably had more technical questions to answer, plus I was a bit shy haha.

The notepad bit makes a lot of sense.  Will stop using fancy IDEs and autocomplete.  I've been working on a lot of projects since I started.  Created about 15 different sites/side projects so far.  Aside from front end work (the day job) I've been learning Python and creating Django web apps. Right now I've had trouble finding co founders for my crazy ideas, hence trying to learn full stack.

Is working on both frontend & backend something you encountered?
If so, would you recommend choosing one over the other, or continue along learning both simultaneously?

If you're ever back in the Wisconsin area and want a free meal, hit me up.  Would love the chance to pick your brain some more.
