### ISSUE TITLE
Regarding position of Older and Newer button in poole/hyde

### ISSUE THREAD

**Issue by dudejavaibhav7** [mdo/ama#269]
Hi, 
Actually my friend is using the hyde theme for his website, the question which arise in my mind after going through the website is the position of Older and Newer button for navigating the pages. My question is : 

1. What was the motivation behind putting older button before newer button ?
2. can they be exchanged ?

Hope to hear from you soon :) ...

**Comment by mdo** [comment]
Linearly, going back is typically on the left and going forward is to the right. At least in LTR languages like English. They can be changed with some manual editing.
