### ISSUE TITLE
Poole/Lanyon & Bootstrap buttons

### ISSUE THREAD

**Issue by gmavrom** [mdo/ama#270]
Hi Mark,

I am using the Lanyon theme in an effort to create a personal website. It's by far my favourite theme aesthetically!

I must note, though, that I am not a developer and most of my "developing" is happening through trial-and-error.

I wanted to add a simple functionality that is the buttons from bootstrap that I see [here](https://v4-alpha.getbootstrap.com/components/buttons/).

I have simply added the line that I saw in the "Getting Started" page of Bootstrap at the ./_includes/head.html as the first .css file loaded.

This, however, results in the default font of the Lanyon theme changing.

Is there an easy way to simply add the button functionality without overriding the font settings of the Lanyon theme?

Any help will be really appreciated!

Best regards,

George

**Comment by mdo** [comment]
You'd need to manually edit the compiled Bootstrap CSS file or customize the build yourself.
