### ISSUE TITLE
What do you think of this copy pasta buffet I made for Bootstrap 4?

### ISSUE THREAD

**Issue by arechsteiner** [mdo/ama#271]
Hey @mdo!

First of all, great job on the progress of Bootstrap 4. I've been leveraging the power of your color system with custom builds and I've had more than one moment where I thought, man this is powerful stuff. I've had my doubts about the spacing and color utility classes but now I use them all the time and they turned out to be a big time saver and allow me to build stuff very quickly. I really enjoy working with Bootstrap 4 as a developer.

I've recently released a components buffet for Bootstrap 4 that I've worked on for quite a while, I was wondering how you like it:

https://hackerthemes.com/bootstrap-buffet/

It's a similar concept to the [cheat sheet I made last year](https://hackerthemes.com/bootstrap-cheatsheet/). I'm not sure if that one ever blipped on your radar. It was really well received so I thought, why build one if I can build two? 😄

Cheers!
@arechsteiner

PS: If you ever come to Barcelona let me know. I'll take you on a bar crawl!

**Comment by mdo** [comment]
I like it!
