### ISSUE TITLE
Would you take a quick glance at my portfolio for the Web Design role? 

### ISSUE THREAD

**Issue by strtw** [mdo/ama#272]
Hi Mark, 

I don't want to be too forward but I've just applied for the Web Designer position you tweeted out: https://boards.greenhouse.io/github/jobs/950380#.WidWKLQ-dE6

I'd appreciate it if you took a quick glance of my portfolio; I think I'd make a great addition to the team. 

http://stuwood.surge.sh/dest/html/index.html

**Comment by mdo** [comment]
Hey thanks for reaching out! I'm not the hiring manager for the role, but I know our design manager responsible for it is looking at all candidates closely :). Best of luck!
