### ISSUE TITLE
Donations to support Bootstrap?

### ISSUE THREAD

**Issue by mind-bending-forks** [mdo/ama#273]
Hi Mark,

I work for a company that uses Bootstrap on its own website and some of its projects for its clients. Each year we donate back to open-source software projects that we have profited from. This year, Bootstrap is one of the projects we have decided to donate to, if that's possible. The donation we would make would be fairly modest, in the region of 100 GBP.  

Please could you let me know:
- Does Bootstrap project accept donations?
- If so, what is the mechanism for making such a donation?
- How would it likely be spent?

Thank you.

**Comment by mind-bending-forks** [comment]
If possible, please you could let me know by 2nd Jan 2018? Otherwise we'll have to reallocate the funds to other open source projects on our donations list. There would still be potential for Bootstrap to get nominated for a donation at the end of 2018. Thank you.

**Comment by mind-bending-forks** [comment]
Happy new year! Sorry, you missed out on a donation from us for this year, so I'll close this issue. If you'd like to be considered for next year's round of donations, please re-open and address the questions above. Thank you.

**Comment by mdo** [comment]
Hey there, I've been on vacation for the last few weeks, so I haven't been watching email or notifications of most repos. We're pretty well set on funds for Bootstrap and don't accept donations at this time. Please redirect those funds to another project :).

**Comment by mind-bending-forks** [comment]
No problem Mark. We'll reallocate the funds this time. Thank you for the reply.
