### ISSUE TITLE
Is Helvetica Neue recommended in font stack?

### ISSUE THREAD

**Issue by bardware** [mdo/ama#275]
Hi @mdo, 

thanks for your blog http://markdotto.com/2018/02/07/github-system-fonts/ 
You write: `As fallback, **Helvetica Neue** and Arial are included`.
The font list under `This font stack has since been updated and iterated upon` reads `font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", **Helvetica**, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`.
It does not contain `Helvetica Neue`. Where is it gone?

**Comment by mdo** [comment]
Dropped it since it's not included in Windows by default and doesn't need to be used for macOS.
