### ISSUE TITLE
Twitter typeahead question

### ISSUE THREAD

**Issue by SumNeuron** [mdo/ama#276]
Hi @mdo,
I have a question about a project you likely no longer work for... but am interested in your response nonetheless.

Twitter's typeahead is pretty popular. Perhaps one of the most requested features is multiple values and in one of the multiple issues in the repo regarding this, you stated something like "we don't have this". It seems pretty clear that it is also something that will not be added. 

I am not here to ask you to add this functionality. 
My question is rather regarding the team's choice to not implement it. 

If so many people want this feature, and adding it is fairly straightforward and does not affect bloodhound, why not add it? If you look at the evolution of these duplicate issues requesting multiple values, they shift from asking to people just sending users elsewhere e.g. select2, or various tag libraries. 

So my question is just to find out the rational behind this decision. I don't mind either way, I just found it curious.

**Comment by mdo** [comment]
I'm unsure how to help here—I've never worked on Twitter's typeahead plugin. That was a different team than myself and Jacob who made Bootstrap. We had our own attempts at things like it in Bootstrap, but that was 4-5 years ago. From our perspective, things like this are heavily dependent on more of your setup—your build tools, languages, front-end templating, etc. It's not something we're experts in or want to maintain.
