### ISSUE TITLE
how can I contact you for sensitive information?

### ISSUE THREAD

**Issue by aizjg** [mdo/ama#278]
So I found a vulnerability on getbootstrap.com but there are 0 emails to contact you guys. 
I tried sending a DM on twitter but got no response :/ 
So how am I able to contact you?

**Comment by mdo** [comment]
You can send me an email with anything—`markdotto@gmail.com`.

**Comment by aizjg** [comment]
I sended you an email :) thanks for the fast reply.

kind regards 
bram
