### ISSUE TITLE
Bootstrap 4.1 navbar background

### ISSUE THREAD

**Issue by cdoole** [mdo/ama#279]
I'm trying to customise the navbar portfolio site I'm trying to build using bootstrap but I can't seem to override the styling for the bg-dark class, I'm currently using the minified css. I would like to be able to continue but every time I try to change the colours in the palette I have chosen I cannot seem to override it even after flushing the dns resolver cache. Is there any way I can do this without having to use the uncompressed version and editing that

**Comment by mdo** [comment]
If you're overriding that class elsewhere, you'll need `!important` at the end. For example:

```
.bg-dark { background-color: red !important; }
```
