### ISSUE TITLE
Installing Lanyon Theme

### ISSUE THREAD

**Issue by NatalieGates** [mdo/ama#294]
I'm have a difficult time installing lanyon. I was able to bundle and serve jekyll without any issues, with the theme minima. When I downloaded lanyon and put it in the same repository and bundled it I receive errors such as gem not found. 

I've followed instructions from several websites that explain how to install themes but nothing is working. Maybe I did something out of order.

**Comment by mdo** [comment]
Lanyon isn't published as a gem, so you cannot install it that way. I haven't had time to update the project to really bake it into a gem theme. As it stands now, you'd have to do a manual install by copying-pasting certain files.
