### ISSUE TITLE
What have you been working on lately?

### ISSUE THREAD

**Issue by amejiarosario** [mdo/ama#295]

**Comment by mdo** [comment]
Here’s a quick rundown!

- [Bootstrap Icons](https://icons.getbootstrap.com)
- [Bootstrap v5](https://https://twbs-bootstrap.netlify.com) (alpha coming soon!)
- GitHub Universe: keynote content, design, and coordination with a small team of designers, comms team members, and execs
- GitHub brand guide: how and when to brand GitHub, using our brand assets, brand attributes, etc (also includes the sites I’ve made to house that information)
- GitHub swag: mostly stickers and planning for merch lines with our team
