### ISSUE TITLE
Recently broken newsfeed?

### ISSUE THREAD

**Issue by ap** [mdo/ama#298]
Did you recently set up some kind of search & replace filter on your newsfeed (or maybe on the whole site?) to turn HTTP URLs into HTTPS ones? Or something like that?

Not only did all the `<id>` values change from `http://www.markdotto.com/...` to `https://markdotto.com/...` (which marks them all as new entries), but the namespace also went from `http://www.w3.org/2005/Atom` to `https://www.w3.org/2005/Atom` – the former being the Atom namespace, and the latter being unknown. So your feed format went from Atom to 🤷‍♀️…

([Feed Validator complains about a number of issues](http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fmarkdotto.com%2Fatom.xml), but most of them are interoperability advice; only the namespace issue makes your feed invalid.)

**Comment by mdo** [comment]
Fixing now, thanks!
