### ISSUE TITLE
Bootstrap example

### ISSUE THREAD

**Issue by pwisker** [mdo/ama#299]
Hi Mark!

I want to know if I can use/buy the blog example https://getbootstrap.com/docs/4.4/examples/blog/ on the Bootstrap website?

Thank you,

Patrick

**Comment by mdo** [comment]
Examples on the Bootstrap docs are all free to use! There's a PR in the works to add a zipped up download for our examples, so in the mean time it's a little bit of copy-pasta and editing required. But have at it!

**Comment by pwisker** [comment]
Would a headless cms combined with the Bootstrap docs result in a fully functioning website?
