### ISSUE TITLE
Bootstrap Figma Icon

### ISSUE THREAD

**Issue by crispouille** [mdo/ama#301]
Hi man,

You would be my life saver. I am basically trying to find a figma library for the bootstrap icons and discovered your project. It's terrific, well done!

While browsering it, I discovered this page : https://blog.getbootstrap.com/2019/11/26/bootstrap-icons/

It actually mention a figma library. Would you be kind enough to share it.

Many, many thanks in advance.

Best,
Paul

**Comment by mdo** [comment]
[The Bootstrap Icons project](https://github.com/twbs/icons) has a link to the Figma in the readme.
