### ISSUE TITLE
Looking for a DAM?

### ISSUE THREAD

**Issue by tae-kim-Frontify** [mdo/ama#304]
Hey Mark,

Strange place to find a sales email, I know. But I don't "really hate" you so I figured email wasn't the way to go.

Jay Zahner mentioned Frontify as the best digital asset management tool and I was curious if you'd like to test out a trial yourself? [Here's how our DAM works](https://vimeo.com/338279444).

Or if you'd prefer examples, we have those too. Let me know which you prefer and I'll send them over!

All the best,
Tae

**Comment by mdo** [comment]
We're all set, thanks!
