### ISSUE TITLE
Why are you not using semicolon in bootstrap?

### ISSUE THREAD

**Issue by rohit2sharma95** [mdo/ama#306]
I have already read your comment here though 🙂 
https://github.com/twbs/bootstrap/discussions/31321#discussioncomment-38890

But you did not tell why you are doing this. As per @Johann-S, he is using your old style.
Sorry to ask it personally here but because you are the maintainer, you know the reason.

**Comment by mdo** [comment]
Not going to re-explain here unfortunately, but Google can find you answers as well as some older Bootstrap issues.
