### ISSUE TITLE
Issue with GitHub font stack

### ISSUE THREAD

**Issue by nikwen** [mdo/ama#307]
Are you still working on the GitHub [font stack](https://markdotto.com/2018/02/07/github-system-fonts/#the-stack)?

Fonts are not centered properly when using Firefox 84 on [Fedora 33](https://getfedora.org/) and I do not know where else to report this issue:

![Screenshot](https://user-images.githubusercontent.com/3309657/103156391-73ee3180-47a8-11eb-8861-16ee37e76c2a.png)

---

# Technical details

Fedora does not ship the `Helvetica` and `Arial` fonts used by GitHub.

Firefox on Fedora uses `Nimbus Sans` as a replacement for `Helvetica`:

![Screenshot](https://user-images.githubusercontent.com/3309657/103156494-5bcae200-47a9-11eb-8a29-9e631cf03ccf.png)

If we remove `Helvetica` from the font declaration, the system uses `Liberation Sans`, which looks okay-ish:

![Screenshot](https://user-images.githubusercontent.com/3309657/103156531-9e8cba00-47a9-11eb-9be8-1029ac91e3c3.png)

---

If you solve this issue at Github, would you mind sharing how you did it? The Chakra UI framework copied the font stack and suffers from the same issue. https://github.com/chakra-ui/chakra-ui/issues/2314

Thank you very much for setting up this AMA repo! :+1:

**Comment by mdo** [comment]
I'm not working on it anymore, no. You'll want to ask around in the Primer org for our open source design system.

**Comment by nikwen** [comment]
Thank you very much, @mdo, for both pointing me in the right direction and for all the great work you do on Bootstrap! Bootstrap has helped me a lot during the years. :+1:
