### ISSUE TITLE
Bootstrap Licence Question

### ISSUE THREAD

**Issue by tebraDev** [mdo/ama#309]
Hey!
I saw your amazing bootstrap template https://getbootstrap.com/docs/5.0/examples/cover/ and decided to use it for my site https://schniide.com/. Basically I changed the footer and the content inside the h1 tag. The metadata in the header are unchanged. Am I allowed to do these changes or must the footer remain unchanged? 
Regards tebra

**Comment by mdo** [comment]
You're free to modify it how you want, without attribution to me :). I should really take that out.
