### ISSUE TITLE
DropDown Issue

### ISSUE THREAD

**Issue by HighlyFavoredBA** [mdo/ama#315]
Hi Mark,

I've been editing my newest internet site, and the drop down menu doesn't appear to close no matter what script I use.  I added data-toggle="dropdown" to one of the drop down links, as well as added $().dropdown('toggle') to my JS.  However the drop down menu still stays open.  Even after clearing my cache.   data-bs-toggle="dropdown"  closes the drop down menu, without scrolling down or up the page.  I've been at this for over a week, and I'm excited to find a solution!  What do you suggest?  :--)

Truly, Andrew

**Comment by mdo** [comment]
The Bootstrap repo is the proper place for bug reports.
