### ISSUE TITLE
BS 5.1.3 issues(?)

### ISSUE THREAD

**Issue by richware** [mdo/ama#317]
I have run into several minor problem regarding converting from scss to sass which I have resolved. I have found a technique to make adjustments to the core bs. I add a custom folder and add my custom sass files that generate into the core css file. Example, I have font-faces that I include so I have created font-face files that handle this process. I have attached.
[font-face.zip](https://github.com/mdo/ama/files/7998202/font-face.zip)

I have developed a CMS and was tired of re-inventing css and came across Bootstrap and started diving into the product and found it useful. As I run into issues or have thoughts how is the best way to convey those ideas and suggestions?

**Comment by mdo** [comment]
Bootstrap has it's own repo and organization here, so you can raise them there. Open an issue for a bug (be sure to read the issue template) or ask others for input in the Discussions tab.
