### ISSUE TITLE
http://markdotto.com/

### ISSUE THREAD

**Issue by 16n** [mdo/ama#41]
I absolutely love the simplicity of your site and would love to know which technology you do use for it? What do you use to make your markdown looks so pretty?

PS: Thank you so much for bootstrap. It is fantastic!!

**Comment by daseinhorn** [comment]
I'm still very interested in your design. Since you update your page (really like it!) would you mind sharing your "old" template?

**Comment by mdo** [comment]
Sorry, I won't be sharing much of any of the previous designs either right now. I've thought about doing Jekyll themes for some of them, but I've no time to do that yet.
