### ISSUE TITLE
Cheeky ask

### ISSUE THREAD

**Issue by domjacks** [mdo/ama#94]
Hi Mark,

I would just like to say nice work with Bootstrap and the GitHub improvements, really cool stuff. I'm a second year CompSci student at Sheffield in the UK and one of the people you probably find weird for actually reading your blog posts.

Anyway, thanks...

...No wait! When I said I would just like to say nice work, that wasn't fully true... I would also like to be really cheeky and ask for some of your cool stickers. Like the GitHub, Atom and Octocat ones ;)

I can send a SASE if that makes it easier?

Cheeeeers,

Dom Jackson

**Comment by amitmerchant1990** [comment]
I am in for this as well @mdo :)
